version: '3.9'

services:
  bridge-api:
    build: .
    ports:
      - "2341:5000"
    env_file:
      - .env
    volumes:
      - ./LOGS:/app/LOGS
      # - ./LOGS:appLogs
    depends_on:
      - postgres
      - redis
    networks:
      - mynetwork

  # PostgreSQL database
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  # Redis server
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  # nginx:
  #   build:
  #     context: ./Nginx
  #     # dockerfile: Dockerfile
  #   volumes:
  #     - static:/static
  #     # - ./Nginx:/app
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - bridge-api
  #   restart: unless-stopped

volumes:
  appLogs:

networks:
  mynetwork:
    driver: bridge
