version: '3.3'

services:
  # PostgreSQL database
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - PostgresDB:/data/postgres

  # Redis server
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_cache:/data/redis

  bridge-api:
    build: .
    ports:
      - "2341:80"
    environment:
      NODE_OPTIONS: "--max-old-space-size=4096"
    env_file:
      - .env
    mem_limit: 4g
    volumes:
      - ./LOGS:/app/LOGS
      - ./:/app
      - /app/node_modules
      # - ./LOGS:appLogs
    depends_on:
      - postgres
      - redis
  # nginx:
  #   build:
  #     context: ./Nginx
  #     # dockerfile: Dockerfile
  #   volumes:
  #     - static:/static
  #     # - ./Nginx:/app
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - bridge-api
  #   restart: unless-stopped

volumes:
  appLogs:
  redis_cache:
  PostgresDB:
  
# networks:
#   mynetwork:
#     driver: bridge
